In [1]:
#24

### IMPORT LIBRARIES

In [3]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

### IMPORT DATASET

In [4]:
dataset = pd.read_csv('Data.csv')
dataset.shape
dataset

# X is Independent Variables (We took COUNTRY, AGE, SALARY as Independent Variable)
X = dataset.iloc[:, :-1].values

# y is Dependent Variables (We took PURCHASED as Dependent Variable)
y = dataset.iloc[:, 3].values

### MISSING VALUE TREATMENT

In [ ]:
df_data.isna()
dataset.isnull().sum()

In [22]:
from sklearn.preprocessing import Imputer
imputer = Imputer(missing_values = 'NaN', strategy = 'mean', axis = 0)
imputer = imputer.fit(X[:, 1:3])
X[:, 1:3] = imputer.transform(X[:, 1:3])

In [ ]:
'''
Updates:
***** Also, for those of you who run into Sklearn related deprecations regarding the imputer class you can use the following modifications:
from sklearn.impute import SimpleImputer
missingvalues = SimpleImputer(missing_values = np.nan, strategy = 'mean', verbose = 0)
missingvalues = missingvalues.fit(X[:, 1:3])
X[:, 1:3]=missingvalues.transform(X[:, 1:3])
'''

In [23]:
X

array([['France', 44.0, 72000.0],
       ['Spain', 27.0, 48000.0],
       ['Germany', 30.0, 54000.0],
       ['Spain', 38.0, 61000.0],
       ['Germany', 40.0, 63777.77777777778],
       ['France', 35.0, 58000.0],
       ['Spain', 38.77777777777778, 52000.0],
       ['France', 48.0, 79000.0],
       ['Germany', 50.0, 83000.0],
       ['France', 37.0, 67000.0]], dtype=object)

### ENCODING CATEGORICAL(TEXT) DATA TO NUMERIC DATA

###### LABELENCODER Convert TEXT Values to NUMERIC Values, which are ACCEPTED by Machine Learning Models


In [25]:
from sklearn.preprocessing import LabelEncoder
labelencoder_X = LabelEncoder()
X[:, 0] = labelencoder_X.fit_transform(X[:, 0])

In [26]:
X

array([[0, 44.0, 72000.0],
       [2, 27.0, 48000.0],
       [1, 30.0, 54000.0],
       [2, 38.0, 61000.0],
       [1, 40.0, 63777.77777777778],
       [0, 35.0, 58000.0],
       [2, 38.77777777777778, 52000.0],
       [0, 48.0, 79000.0],
       [1, 50.0, 83000.0],
       [0, 37.0, 67000.0]], dtype=object)

In [29]:
# Encoding the Dependent Variable y
labelencoder_y = LabelEncoder()
y = labelencoder_y.fit_transform(y)

### SPLITTING DATASET INTO TRAINING & TEST SET

In [30]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

### FEATURE SCALING

In [ ]:
''' When values in our data are not on same scale
eg. Age = 44 & Salary = $7000
In above case Age is an 2 digit value & Salary is 4 digit
So in such cases we need to do FEATURE SCALING
And bring them on same Level '''

In [ ]:
''' CAUTION:
# Need to remember that FACTOR is not numeric and will give error when we FEATURE SCALE.
# So we need to apply FEATURE SCALING only on the NUMERIC COLUMNS '''

In [36]:
from sklearn.preprocessing import StandardScaler

In [37]:
sc_X = StandardScaler()
X_train = sc_X.fit_transform(X_train)
X_test = sc_X.transform(X_test)

In [38]:
X_train

array([[-1.        ,  2.64575131, -0.77459667,  0.26306757,  0.12381479],
       [ 1.        , -0.37796447, -0.77459667, -0.25350148,  0.46175632],
       [-1.        , -0.37796447,  1.29099445, -1.97539832, -1.53093341],
       [-1.        , -0.37796447,  1.29099445,  0.05261351, -1.11141978],
       [ 1.        , -0.37796447, -0.77459667,  1.64058505,  1.7202972 ],
       [-1.        , -0.37796447,  1.29099445, -0.0813118 , -0.16751412],
       [ 1.        , -0.37796447, -0.77459667,  0.95182631,  0.98614835],
       [ 1.        , -0.37796447, -0.77459667, -0.59788085, -0.48214934]])

In [39]:
X_test

array([[-1.        ,  2.64575131, -0.77459667, -1.45882927, -0.90166297],
       [-1.        ,  2.64575131, -0.77459667,  1.98496442,  2.13981082]])

In [41]:
y_train

array([1, 1, 1, 0, 1, 0, 0, 1])

In [42]:
y_test

array([0, 0])